language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - apt-get update && apt-get install -y unzip
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install
  - cp .env.example .env

script:
  - vendor/bin/phpunit --coverage-text --colors